-- V2__users.sql
--
-- Accounts and the verification secrets that activate them (FR-A1 - FR-A5, FR-A7).
--
-- Written by hand, not generated: this file is the authority on the schema and
-- Hibernate only validates against it (ddl-auto=validate). JOINED inheritance gives one
-- `users` row per account plus a row in the table for its role, so the shared columns
-- are declared, constrained and indexed exactly once.
--
-- Enum columns are varchar + CHECK rather than a Postgres enum type: adding a value to a
-- Postgres enum is a schema change that cannot run inside every transaction, while a
-- CHECK is edited by an ordinary later migration. Hibernate stores the enum name.

CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    role               VARCHAR(10)  NOT NULL,
    email              VARCHAR(254) NOT NULL,
    password_hash      VARCHAR(100) NOT NULL,
    full_name          VARCHAR(150) NOT NULL,
    phone_number       VARCHAR(20)  NOT NULL,
    email_verified     BOOLEAN      NOT NULL DEFAULT FALSE,
    phone_verified     BOOLEAN      NOT NULL DEFAULT FALSE,
    preferred_language VARCHAR(2)   NOT NULL DEFAULT 'EN',
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING_VERIFICATION',
    last_login_at      TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT ck_users_role CHECK (role IN ('TUTOR', 'PARENT', 'ADMIN')),
    CONSTRAINT ck_users_preferred_language CHECK (preferred_language IN ('EN', 'SI', 'TA')),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETED'))
);

-- Login and registration both hit these. The unique constraint provides the index, and
-- it is the real guarantee behind the "email already registered" check: two concurrent
-- registrations cannot both pass an application-level look-up. Email is stored
-- lower-cased by the entity, so a plain unique index is case-insensitive in effect.
ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uq_users_phone_number UNIQUE (phone_number);

-- Admin listings and moderation queues filter by role and status.
CREATE INDEX idx_users_role_status ON users (role, status);

-- One table per role. Empty of their own columns today: Tutor, Parent and Admin add
-- nothing beyond the shared account contract yet. The tables still earn their place -
-- they are what makes the subtype a fact in the database, and Phase 2 hangs the tutor's
-- published profile off `tutors`.
CREATE TABLE tutors (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_tutors_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE parents (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_parents_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE admins (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_admins_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

-- A parent may manage many children (FR-A5). grade and exam_level are free text until
-- Phase 2 lands the translatable exam-level reference table; a later migration converts
-- exam_level into a foreign key so search filters and child profiles share one
-- vocabulary.
CREATE TABLE child_profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    parent_id  BIGINT        NOT NULL,
    name       VARCHAR(150)  NOT NULL,
    grade      VARCHAR(50)   NOT NULL,
    exam_level VARCHAR(50)   NOT NULL,
    school     VARCHAR(200),
    notes      VARCHAR(1000),

    CONSTRAINT fk_child_profiles_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE CASCADE
);

CREATE INDEX idx_child_profiles_parent_id ON child_profiles (parent_id);

-- Verification secrets. Both store a digest, never the value that was sent.
--
-- The email token is a SHA-256 of a long random string: deterministic, so the link can be
-- looked up by its digest alone. The OTP is six digits under a salted BCrypt hash, so it
-- is found by user and compared - which is why only one of the two columns is unique.
CREATE TABLE email_verification_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id       BIGINT      NOT NULL,
    token_hash    VARCHAR(64) NOT NULL,
    expires_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at   TIMESTAMP(6) WITH TIME ZONE,
    attempt_count INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT uq_email_verification_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_email_verification_tokens_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens (user_id, created_at DESC);

CREATE TABLE phone_otps (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id       BIGINT       NOT NULL,
    code_hash     VARCHAR(100) NOT NULL,
    expires_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at   TIMESTAMP(6) WITH TIME ZONE,
    attempt_count INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_phone_otps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_phone_otps_attempt_count CHECK (attempt_count >= 0)
);

-- Serves both "the live code for this user" and the hourly send cap.
CREATE INDEX idx_phone_otps_user_id ON phone_otps (user_id, created_at DESC);
