-- V3__auth_tokens.sql
--
-- The two secrets the sign-in flows need beyond registration (FR-A4, FR-A6):
-- revocable refresh tokens and single-use password-reset tokens.
--
-- Both store a SHA-256 digest, never the value handed to the user. The digest is
-- deterministic because the client sends back only the token — there is no id to look the
-- row up by — and that is safe precisely because these tokens are 256 bits of randomness.
-- A short, guessable secret like the six-digit OTP is salted instead (see phone_otps).

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Null while the session is live. Set by logout, by rotation on refresh, and by
    -- anything that must end every session at once (password reset, account deletion).
    revoked_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Serves "end every session for this user", which is the only query that is not by digest.
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id       BIGINT      NOT NULL,
    token_hash    VARCHAR(64) NOT NULL,
    expires_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at   TIMESTAMP(6) WITH TIME ZONE,
    attempt_count INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_password_reset_tokens_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id, created_at DESC);
