-- V4__reference_data.sql
--
-- The normalised vocabulary of the platform: subjects, exam levels, syllabuses and
-- areas, each translated into Sinhala, Tamil and English (architecture §9: reference
-- data is never free text in a search filter).
--
-- Two decisions shape this file.
--
-- 1. `code` is the identifier, not `id`. Codes are what the API exposes, what a tutor
--    profile and a search filter are stored against, and what the seeds below join on -
--    so the data can be written without knowing a single generated key, and a later
--    migration can add a district without renumbering anything.
--
-- 2. Translations live in a collection table per entity, keyed (owner, language). One
--    row per language rather than three name columns: adding a fourth language is then
--    a data migration, and a missing translation is an absent row the application can
--    fall back from, not a NULL column every query has to coalesce.
--
-- Adding more of Sri Lanka later is a new V<n>__ file with more VALUES rows. It is
-- never a code change.

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

CREATE TABLE subjects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    code          VARCHAR(60) NOT NULL,
    display_order INTEGER     NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_subjects_code UNIQUE (code)
);

-- Every read is "the active list, in display order". The index covers it.
CREATE INDEX idx_subjects_active_display_order ON subjects (active, display_order);

CREATE TABLE subject_translations (
    subject_id BIGINT       NOT NULL,
    language   VARCHAR(2)   NOT NULL,
    name       VARCHAR(200) NOT NULL,

    CONSTRAINT pk_subject_translations PRIMARY KEY (subject_id, language),
    CONSTRAINT fk_subject_translations_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
    CONSTRAINT ck_subject_translations_language CHECK (language IN ('EN', 'SI', 'TA'))
);

CREATE TABLE exam_levels (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    code          VARCHAR(60) NOT NULL,
    display_order INTEGER     NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_exam_levels_code UNIQUE (code)
);

CREATE INDEX idx_exam_levels_active_display_order ON exam_levels (active, display_order);

CREATE TABLE exam_level_translations (
    exam_level_id BIGINT       NOT NULL,
    language      VARCHAR(2)   NOT NULL,
    name          VARCHAR(200) NOT NULL,

    CONSTRAINT pk_exam_level_translations PRIMARY KEY (exam_level_id, language),
    CONSTRAINT fk_exam_level_translations_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_levels (id) ON DELETE CASCADE,
    CONSTRAINT ck_exam_level_translations_language CHECK (language IN ('EN', 'SI', 'TA'))
);

CREATE TABLE syllabuses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    code          VARCHAR(60) NOT NULL,
    display_order INTEGER     NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_syllabuses_code UNIQUE (code)
);

CREATE INDEX idx_syllabuses_active_display_order ON syllabuses (active, display_order);

CREATE TABLE syllabus_translations (
    syllabus_id BIGINT       NOT NULL,
    language    VARCHAR(2)   NOT NULL,
    name        VARCHAR(200) NOT NULL,

    CONSTRAINT pk_syllabus_translations PRIMARY KEY (syllabus_id, language),
    CONSTRAINT fk_syllabus_translations_syllabus FOREIGN KEY (syllabus_id) REFERENCES syllabuses (id) ON DELETE CASCADE,
    CONSTRAINT ck_syllabus_translations_language CHECK (language IN ('EN', 'SI', 'TA'))
);

-- Areas are self-referencing: a district has no parent, a town has exactly one. The
-- CHECK is what makes that a fact in the database rather than a convention the
-- application is trusted to keep.
--
-- Coordinates are NUMERIC(9,6) - decimal degrees, WGS 84, six places. Nothing sorts by
-- distance yet (Phase 3 does), but coordinates collected from the start are coordinates
-- nobody has to backfill for the table search depends on.
CREATE TABLE areas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    code          VARCHAR(60)  NOT NULL,
    display_order INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    type          VARCHAR(20)  NOT NULL,
    parent_id     BIGINT,
    latitude      NUMERIC(9,6) NOT NULL,
    longitude     NUMERIC(9,6) NOT NULL,

    CONSTRAINT uq_areas_code UNIQUE (code),
    CONSTRAINT fk_areas_parent FOREIGN KEY (parent_id) REFERENCES areas (id),
    CONSTRAINT ck_areas_type CHECK (type IN ('DISTRICT', 'TOWN')),
    CONSTRAINT ck_areas_hierarchy CHECK (
        (type = 'DISTRICT' AND parent_id IS NULL)
        OR (type = 'TOWN' AND parent_id IS NOT NULL)),
    CONSTRAINT ck_areas_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_areas_longitude CHECK (longitude BETWEEN -180 AND 180)
);

-- "The towns of this district, in order" and "all active districts, in order".
CREATE INDEX idx_areas_parent_id ON areas (parent_id, display_order);
CREATE INDEX idx_areas_type_active ON areas (type, active, display_order);

CREATE TABLE area_translations (
    area_id  BIGINT       NOT NULL,
    language VARCHAR(2)   NOT NULL,
    name     VARCHAR(200) NOT NULL,

    CONSTRAINT pk_area_translations PRIMARY KEY (area_id, language),
    CONSTRAINT fk_area_translations_area FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE,
    CONSTRAINT ck_area_translations_language CHECK (language IN ('EN', 'SI', 'TA'))
);

-- ---------------------------------------------------------------------------
-- Seed data
--
-- Each value is written once, on one line, with its three names side by side - so a
-- missing or placeholder translation is visible while reading rather than discoverable
-- only by querying. The trailing CROSS JOIN LATERAL turns those three columns into the
-- three rows the schema wants.
-- ---------------------------------------------------------------------------

-- Exam levels. The Sri Lankan ladder, plus the two rungs outside the school system that
-- tutors on this platform actually teach (professional bodies, language and skills).
INSERT INTO exam_levels (code, display_order, active, created_at, updated_at)
SELECT v.code, v.display_order, TRUE, NOW(), NOW()
FROM (VALUES
    ('GRADE_5_SCHOLARSHIP', 10),
    ('GRADE_6_TO_9',        20),
    ('GCE_OL',              30),
    ('GCE_AL',              40),
    ('UNDERGRADUATE',       50),
    ('PROFESSIONAL',        60),
    ('LANGUAGE_AND_SKILLS', 70)
) AS v(code, display_order);

INSERT INTO exam_level_translations (exam_level_id, language, name)
SELECT e.id, t.language, t.name
FROM exam_levels e
JOIN (VALUES
    ('GRADE_5_SCHOLARSHIP', 'Grade 5 Scholarship', '5 ශ්‍රේණිය ශිෂ්‍යත්වය', '5 ஆம் ஆண்டு புலமைப்பரிசில்'),
    ('GRADE_6_TO_9',        'Grades 6-9',          '6-9 ශ්‍රේණි',          '6-9 ஆம் வகுப்புகள்'),
    ('GCE_OL',              'GCE O/L',             'අ.පො.ස. සාමාන්‍ය පෙළ', 'க.பொ.த. சாதாரண தரம்'),
    ('GCE_AL',              'GCE A/L',             'අ.පො.ස. උසස් පෙළ',     'க.பொ.த. உயர் தரம்'),
    ('UNDERGRADUATE',       'Undergraduate',       'උපාධි අපේක්‍ෂක',        'இளங்கலை'),
    ('PROFESSIONAL',        'Professional',        'වෘත්තීය',              'தொழில்சார்'),
    ('LANGUAGE_AND_SKILLS', 'Language & Skills',   'භාෂා හා කුසලතා',       'மொழி மற்றும் திறன்கள்')
) AS v(code, en, si, ta) ON v.code = e.code
CROSS JOIN LATERAL (VALUES ('EN', v.en), ('SI', v.si), ('TA', v.ta)) AS t(language, name);

-- Syllabuses. National is split by medium because in Sri Lanka that is a real difference
-- in the material a tutor works from, not merely the language they speak in class.
INSERT INTO syllabuses (code, display_order, active, created_at, updated_at)
SELECT v.code, v.display_order, TRUE, NOW(), NOW()
FROM (VALUES
    ('NATIONAL_SINHALA',  10),
    ('NATIONAL_TAMIL',    20),
    ('NATIONAL_ENGLISH',  30),
    ('CAMBRIDGE',         40),
    ('EDEXCEL',           50),
    ('PROFESSIONAL_BODY', 60),
    ('OTHER',             70)
) AS v(code, display_order);

INSERT INTO syllabus_translations (syllabus_id, language, name)
SELECT s.id, t.language, t.name
FROM syllabuses s
JOIN (VALUES
    ('NATIONAL_SINHALA',  'National (Sinhala medium)',    'ජාතික (සිංහල මාධ්‍යය)',     'தேசிய (சிங்கள மொழிமூலம்)'),
    ('NATIONAL_TAMIL',    'National (Tamil medium)',      'ජාතික (දෙමළ මාධ්‍යය)',      'தேசிய (தமிழ் மொழிமூலம்)'),
    ('NATIONAL_ENGLISH',  'National (English medium)',    'ජාතික (ඉංග්‍රීසි මාධ්‍යය)', 'தேசிய (ஆங்கில மொழிமூலம்)'),
    ('CAMBRIDGE',         'Cambridge',                    'කේම්බ්‍රිජ්',                'கேம்பிரிட்ஜ்'),
    ('EDEXCEL',           'Edexcel',                      'එඩෙක්සෙල්',                 'எடெக்சல்'),
    ('PROFESSIONAL_BODY', 'Professional (CIMA/ACCA/AAT)', 'වෘත්තීය (CIMA/ACCA/AAT)',   'தொழில்சார் (CIMA/ACCA/AAT)'),
    ('OTHER',             'Other',                        'වෙනත්',                     'பிற')
) AS v(code, en, si, ta) ON v.code = s.code
CROSS JOIN LATERAL (VALUES ('EN', v.en), ('SI', v.si), ('TA', v.ta)) AS t(language, name);

-- Subjects.
--
-- Flat on purpose. Subjects that differ between exam levels are genuinely different
-- subjects - O/L Mathematics and A/L Combined Mathematics are not the same thing - so
-- the level is not an attribute of the subject. display_order carries the grouping a
-- syllabus would: 100s O/L core, 200s O/L optional baskets, 300s languages, 400s-600s
-- the A/L streams, 700s the subjects every A/L candidate sits, 800s professional,
-- 900s skills taught outside the exam system.
INSERT INTO subjects (code, display_order, active, created_at, updated_at)
SELECT v.code, v.display_order, TRUE, NOW(), NOW()
FROM (VALUES
    ('SINHALA_LANGUAGE',  100),
    ('TAMIL_LANGUAGE',    105),
    ('ENGLISH_LANGUAGE',  110),
    ('MATHEMATICS',       115),
    ('SCIENCE',           120),
    ('HISTORY',           125),
    ('BUDDHISM',          130),
    ('HINDUISM',          135),
    ('ISLAM',             140),
    ('CHRISTIANITY',      145),
    ('CATHOLICISM',       150),
    ('BUSINESS_AND_ACCOUNTING_STUDIES',      200),
    ('GEOGRAPHY',                            205),
    ('CIVIC_EDUCATION',                      210),
    ('ENTREPRENEURSHIP_STUDIES',             215),
    ('ICT',                                  220),
    ('HEALTH_AND_PHYSICAL_EDUCATION',        225),
    ('AGRICULTURE_AND_FOOD_TECHNOLOGY',      230),
    ('HOME_ECONOMICS',                       235),
    ('ART',                                  240),
    ('DANCING',                              245),
    ('ORIENTAL_MUSIC',                       250),
    ('WESTERN_MUSIC',                        255),
    ('DRAMA_AND_THEATRE',                    260),
    ('ENGLISH_LITERATURE',                   265),
    ('SINHALA_LITERATURE',                   270),
    ('TAMIL_LITERATURE',                     275),
    ('COMMUNICATION_AND_MEDIA_STUDIES',      280),
    ('DESIGN_AND_CONSTRUCTION_TECHNOLOGY',   285),
    ('DESIGN_AND_MECHANICAL_TECHNOLOGY',     290),
    ('ELECTRICAL_AND_ELECTRONIC_TECHNOLOGY', 295),
    ('SECOND_LANGUAGE_SINHALA', 300),
    ('SECOND_LANGUAGE_TAMIL',   305),
    ('PALI',                    310),
    ('SANSKRIT',                315),
    ('FRENCH',                  320),
    ('GERMAN',                  325),
    ('JAPANESE',                330),
    ('KOREAN',                  335),
    ('CHINESE',                 340),
    ('ARABIC',                  345),
    ('HINDI',                   350),
    ('COMBINED_MATHEMATICS', 400),
    ('PHYSICS',              405),
    ('CHEMISTRY',            410),
    ('HIGHER_MATHEMATICS',   415),
    ('BIOLOGY',              450),
    ('AGRICULTURAL_SCIENCE', 455),
    ('BUSINESS_STUDIES',     500),
    ('ACCOUNTING',           505),
    ('ECONOMICS',            510),
    ('BUSINESS_STATISTICS',  515),
    ('POLITICAL_SCIENCE',           550),
    ('LOGIC_AND_SCIENTIFIC_METHOD', 555),
    ('BUDDHIST_CIVILIZATION',       560),
    ('HINDU_CIVILIZATION',          565),
    ('ISLAMIC_CIVILIZATION',        570),
    ('CHRISTIAN_CIVILIZATION',      575),
    ('ENGINEERING_TECHNOLOGY', 650),
    ('BIOSYSTEMS_TECHNOLOGY',  655),
    ('SCIENCE_FOR_TECHNOLOGY', 660),
    ('GENERAL_ENGLISH',                700),
    ('GENERAL_INFORMATION_TECHNOLOGY', 705),
    ('COMMON_GENERAL_TEST',            710),
    ('CIMA',         800),
    ('ACCA',         805),
    ('AAT',          810),
    ('CA_SRI_LANKA', 815),
    ('CIM',          820),
    ('CMA',          825),
    ('SPOKEN_ENGLISH',       900),
    ('IELTS',                905),
    ('SPEECH_AND_DRAMA',     910),
    ('COMPUTER_PROGRAMMING', 915),
    ('GRAPHIC_DESIGN',       920)
) AS v(code, display_order);

-- Professional acronyms (CIMA, ACCA, AAT, CIM, CMA, IELTS) are proper nouns and stay in
-- Latin script in all three languages. That is the correct rendering, not a placeholder.
INSERT INTO subject_translations (subject_id, language, name)
SELECT s.id, t.language, t.name
FROM subjects s
JOIN (VALUES
    ('SINHALA_LANGUAGE', 'Sinhala Language & Literature', 'සිංහල භාෂාව හා සාහිත්‍යය', 'சிங்கள மொழியும் இலக்கியமும்'),
    ('TAMIL_LANGUAGE',   'Tamil Language & Literature',   'දෙමළ භාෂාව හා සාහිත්‍යය',  'தமிழ் மொழியும் இலக்கியமும்'),
    ('ENGLISH_LANGUAGE', 'English Language',              'ඉංග්‍රීසි භාෂාව',          'ஆங்கில மொழி'),
    ('MATHEMATICS',      'Mathematics',                   'ගණිතය',                    'கணிதம்'),
    ('SCIENCE',          'Science',                       'විද්‍යාව',                 'விஞ்ஞானம்'),
    ('HISTORY',          'History',                       'ඉතිහාසය',                  'வரலாறு'),
    ('BUDDHISM',         'Buddhism',                      'බුද්ධ ධර්මය',              'பௌத்தம்'),
    ('HINDUISM',         'Hinduism',                      'හින්දු ධර්මය',             'இந்து சமயம்'),
    ('ISLAM',            'Islam',                         'ඉස්ලාම් ධර්මය',            'இஸ்லாம்'),
    ('CHRISTIANITY',     'Christianity',                  'ක්‍රිස්තු ධර්මය',          'கிறிஸ்தவம்'),
    ('CATHOLICISM',      'Catholicism',                   'කතෝලික ධර්මය',             'கத்தோலிக்கம்'),
    ('BUSINESS_AND_ACCOUNTING_STUDIES',      'Business & Accounting Studies',           'ව්‍යාපාර හා ගිණුම්කරණ අධ්‍යයනය',      'வியாபார மற்றும் கணக்கியல் கல்வி'),
    ('GEOGRAPHY',                            'Geography',                               'භූගෝල විද්‍යාව',                      'புவியியல்'),
    ('CIVIC_EDUCATION',                      'Civic Education',                         'පුරවැසි අධ්‍යාපනය',                   'குடியியல் கல்வி'),
    ('ENTREPRENEURSHIP_STUDIES',             'Entrepreneurship Studies',                'ව්‍යවසායකත්ව අධ්‍යයනය',               'தொழில்முனைவுக் கல்வி'),
    ('ICT',                                  'Information & Communication Technology',  'තොරතුරු හා සන්නිවේදන තාක්‍ෂණය',       'தகவல் மற்றும் தொடர்பாடல் தொழினுட்பம்'),
    ('HEALTH_AND_PHYSICAL_EDUCATION',        'Health & Physical Education',             'සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය',         'சுகாதாரமும் உடற்கல்வியும்'),
    ('AGRICULTURE_AND_FOOD_TECHNOLOGY',      'Agriculture & Food Technology',           'කෘෂි හා ආහාර තාක්‍ෂණය',               'விவசாய மற்றும் உணவுத் தொழினுட்பம்'),
    ('HOME_ECONOMICS',                       'Home Economics',                          'ගෘහ ආර්ථික විද්‍යාව',                 'இல்லப் பொருளியல்'),
    ('ART',                                  'Art',                                     'චිත්‍ර කලාව',                         'ஓவியக் கலை'),
    ('DANCING',                              'Dancing',                                 'නර්තනය',                              'நடனம்'),
    ('ORIENTAL_MUSIC',                       'Oriental Music',                          'පෙරදිග සංගීතය',                       'கீழைத்தேய இசை'),
    ('WESTERN_MUSIC',                        'Western Music',                           'බටහිර සංගීතය',                        'மேலைத்தேய இசை'),
    ('DRAMA_AND_THEATRE',                    'Drama & Theatre',                         'නාට්‍ය හා රංග කලාව',                  'நாடகமும் அரங்கியலும்'),
    ('ENGLISH_LITERATURE',                   'English Literature',                      'ඉංග්‍රීසි සාහිත්‍යය',                 'ஆங்கில இலக்கியம்'),
    ('SINHALA_LITERATURE',                   'Sinhala Literature',                      'සිංහල සාහිත්‍යය',                     'சிங்கள இலக்கியம்'),
    ('TAMIL_LITERATURE',                     'Tamil Literature',                        'දෙමළ සාහිත්‍යය',                      'தமிழ் இலக்கியம்'),
    ('COMMUNICATION_AND_MEDIA_STUDIES',      'Communication & Media Studies',           'සන්නිවේදනය හා මාධ්‍ය අධ්‍යයනය',       'தொடர்பாடலும் ஊடகக் கல்வியும்'),
    ('DESIGN_AND_CONSTRUCTION_TECHNOLOGY',   'Design & Construction Technology',        'නිර්මාණ හා ඉදිකිරීම් තාක්‍ෂණවේදය',    'வடிவமைப்பு மற்றும் நிர்மாணத் தொழினுட்பம்'),
    ('DESIGN_AND_MECHANICAL_TECHNOLOGY',     'Design & Mechanical Technology',          'නිර්මාණ හා යාන්ත්‍රික තාක්‍ෂණවේදය',   'வடிவமைப்பு மற்றும் இயந்திரத் தொழினுட்பம்'),
    ('ELECTRICAL_AND_ELECTRONIC_TECHNOLOGY', 'Electrical & Electronic Technology',      'විදුලි හා ඉලෙක්ට්‍රොනික තාක්‍ෂණවේදය', 'மின் மற்றும் இலத்திரனியல் தொழினுட்பம்'),
    ('SECOND_LANGUAGE_SINHALA', 'Sinhala (Second Language)', 'සිංහල (දෙවන භාෂාව)', 'சிங்களம் (இரண்டாம் மொழி)'),
    ('SECOND_LANGUAGE_TAMIL',   'Tamil (Second Language)',   'දෙමළ (දෙවන භාෂාව)',  'தமிழ் (இரண்டாம் மொழி)'),
    ('PALI',                    'Pali',                      'පාලි',               'பாளி'),
    ('SANSKRIT',                'Sanskrit',                  'සංස්කෘත',            'சமஸ்கிருதம்'),
    ('FRENCH',                  'French',                    'ප්‍රංශ',             'பிரெஞ்சு'),
    ('GERMAN',                  'German',                    'ජර්මන්',             'ஜேர்மன்'),
    ('JAPANESE',                'Japanese',                  'ජපන්',               'ஜப்பானியம்'),
    ('KOREAN',                  'Korean',                    'කොරියානු',           'கொரியம்'),
    ('CHINESE',                 'Chinese',                   'චීන',                'சீனம்'),
    ('ARABIC',                  'Arabic',                    'අරාබි',              'அரபு'),
    ('HINDI',                   'Hindi',                     'හින්දි',             'இந்தி'),
    ('COMBINED_MATHEMATICS', 'Combined Mathematics', 'සංයුක්ත ගණිතය',  'இணைந்த கணிதம்'),
    ('PHYSICS',              'Physics',              'භෞතික විද්‍යාව', 'பௌதிகவியல்'),
    ('CHEMISTRY',            'Chemistry',            'රසායන විද්‍යාව', 'இரசாயனவியல்'),
    ('HIGHER_MATHEMATICS',   'Higher Mathematics',   'උසස් ගණිතය',     'உயர் கணிதம்'),
    ('BIOLOGY',              'Biology',              'ජීව විද්‍යාව',   'உயிரியல்'),
    ('AGRICULTURAL_SCIENCE', 'Agricultural Science', 'කෘෂි විද්‍යාව',  'விவசாய விஞ்ஞானம்'),
    ('BUSINESS_STUDIES',     'Business Studies',     'ව්‍යාපාර අධ්‍යයනය',  'வியாபாரக் கல்வி'),
    ('ACCOUNTING',           'Accounting',           'ගිණුම්කරණය',         'கணக்கியல்'),
    ('ECONOMICS',            'Economics',            'ආර්ථික විද්‍යාව',    'பொருளியல்'),
    ('BUSINESS_STATISTICS',  'Business Statistics',  'ව්‍යාපාර සංඛ්‍යානය', 'வியாபாரப் புள்ளியியல்'),
    ('POLITICAL_SCIENCE',           'Political Science',         'දේශපාලන විද්‍යාව',                    'அரசறிவியல்'),
    ('LOGIC_AND_SCIENTIFIC_METHOD', 'Logic & Scientific Method', 'තර්කශාස්ත්‍රය හා විද්‍යාත්මක ක්‍රමය', 'தர்க்கமும் விஞ்ஞான முறையும்'),
    ('BUDDHIST_CIVILIZATION',       'Buddhist Civilization',     'බෞද්ධ ශිෂ්ටාචාරය',                    'பௌத்த நாகரிகம்'),
    ('HINDU_CIVILIZATION',          'Hindu Civilization',        'හින්දු ශිෂ්ටාචාරය',                   'இந்து நாகரிகம்'),
    ('ISLAMIC_CIVILIZATION',        'Islamic Civilization',      'ඉස්ලාම් ශිෂ්ටාචාරය',                  'இஸ்லாமிய நாகரிகம்'),
    ('CHRISTIAN_CIVILIZATION',      'Christian Civilization',    'ක්‍රිස්තියානි ශිෂ්ටාචාරය',            'கிறிஸ்தவ நாகரிகம்'),
    ('ENGINEERING_TECHNOLOGY', 'Engineering Technology', 'ඉංජිනේරු තාක්‍ෂණවේදය',      'பொறியியல் தொழினுட்பம்'),
    ('BIOSYSTEMS_TECHNOLOGY',  'Bio-systems Technology', 'ජෛව පද්ධති තාක්‍ෂණවේදය',    'உயிர் அமைப்புத் தொழினுட்பம்'),
    ('SCIENCE_FOR_TECHNOLOGY', 'Science for Technology', 'තාක්‍ෂණවේදය සඳහා විද්‍යාව', 'தொழினுட்பத்துக்கான விஞ்ஞானம்'),
    ('GENERAL_ENGLISH',                'General English',                'සාමාන්‍ය ඉංග්‍රීසි',        'பொது ஆங்கிலம்'),
    ('GENERAL_INFORMATION_TECHNOLOGY', 'General Information Technology', 'සාමාන්‍ය තොරතුරු තාක්‍ෂණය', 'பொதுத் தகவல் தொழினுட்பம்'),
    ('COMMON_GENERAL_TEST',            'Common General Test',            'පොදු සාමාන්‍ය පරීක්‍ෂණය',   'பொது அறிவுத் தேர்வு'),
    ('CIMA',         'CIMA',         'CIMA',          'CIMA'),
    ('ACCA',         'ACCA',         'ACCA',          'ACCA'),
    ('AAT',          'AAT',          'AAT',           'AAT'),
    ('CA_SRI_LANKA', 'CA Sri Lanka', 'CA ශ්‍රී ලංකා', 'CA இலங்கை'),
    ('CIM',          'CIM',          'CIM',           'CIM'),
    ('CMA',          'CMA',          'CMA',           'CMA'),
    ('SPOKEN_ENGLISH',       'Spoken English',       'කථන ඉංග්‍රීසි',       'பேச்சு ஆங்கிலம்'),
    ('IELTS',                'IELTS',                'IELTS',               'IELTS'),
    ('SPEECH_AND_DRAMA',     'Speech & Drama',       'කථනය හා නාට්‍ය',      'பேச்சும் நாடகமும்'),
    ('COMPUTER_PROGRAMMING', 'Computer Programming', 'පරිගණක ක්‍රමලේඛනය',   'கணினி நிரலாக்கம்'),
    ('GRAPHIC_DESIGN',       'Graphic Design',       'චිත්‍රක නිර්මාණකරණය', 'வரைகலை வடிவமைப்பு')
) AS v(code, en, si, ta) ON v.code = s.code
CROSS JOIN LATERAL (VALUES ('EN', v.en), ('SI', v.si), ('TA', v.ta)) AS t(language, name);

-- Areas: the three pilot districts. Town codes carry their district as a prefix because
-- town names repeat across Sri Lanka, and this table is meant to grow to cover it.
INSERT INTO areas (code, display_order, active, type, parent_id, latitude, longitude, created_at, updated_at)
SELECT v.code, v.display_order, TRUE, 'DISTRICT', NULL, v.latitude, v.longitude, NOW(), NOW()
FROM (VALUES
    ('COLOMBO',  10, 6.927100, 79.861200),
    ('GAMPAHA',  20, 7.091700, 79.999700),
    ('KALUTARA', 30, 6.585400, 79.960700)
) AS v(code, display_order, latitude, longitude);

INSERT INTO areas (code, display_order, active, type, parent_id, latitude, longitude, created_at, updated_at)
SELECT v.code, v.display_order, TRUE, 'TOWN', d.id, v.latitude, v.longitude, NOW(), NOW()
FROM (VALUES
    ('COLOMBO', 'COLOMBO_CITY',           10, 6.927100, 79.861200),
    ('COLOMBO', 'COLOMBO_BAMBALAPITIYA',  20, 6.893600, 79.856700),
    ('COLOMBO', 'COLOMBO_BORELLA',        30, 6.914700, 79.877800),
    ('COLOMBO', 'COLOMBO_WELLAWATTE',     40, 6.874700, 79.860800),
    ('COLOMBO', 'COLOMBO_DEHIWALA',       50, 6.851100, 79.865300),
    ('COLOMBO', 'COLOMBO_MOUNT_LAVINIA',  60, 6.838900, 79.865300),
    ('COLOMBO', 'COLOMBO_MORATUWA',       70, 6.773000, 79.881600),
    ('COLOMBO', 'COLOMBO_NUGEGODA',       80, 6.864900, 79.899700),
    ('COLOMBO', 'COLOMBO_NAWALA',         90, 6.879200, 79.893900),
    ('COLOMBO', 'COLOMBO_RAJAGIRIYA',    100, 6.909700, 79.895100),
    ('COLOMBO', 'COLOMBO_BATTARAMULLA',  110, 6.899400, 79.918700),
    ('COLOMBO', 'COLOMBO_KOTTE',         120, 6.888500, 79.918600),
    ('COLOMBO', 'COLOMBO_MAHARAGAMA',    130, 6.848200, 79.926700),
    ('COLOMBO', 'COLOMBO_KOTTAWA',       140, 6.841100, 79.965300),
    ('COLOMBO', 'COLOMBO_PILIYANDALA',   150, 6.801600, 79.922500),
    ('COLOMBO', 'COLOMBO_KESBEWA',       160, 6.795500, 79.939400),
    ('COLOMBO', 'COLOMBO_HOMAGAMA',      170, 6.844100, 80.002400),
    ('COLOMBO', 'COLOMBO_MALABE',        180, 6.906100, 79.970000),
    ('COLOMBO', 'COLOMBO_KADUWELA',      190, 6.933300, 79.983300),
    ('COLOMBO', 'COLOMBO_KOLONNAWA',     200, 6.933300, 79.883300),
    ('COLOMBO', 'COLOMBO_HANWELLA',      210, 6.899000, 80.083800),
    ('COLOMBO', 'COLOMBO_PADUKKA',       220, 6.844700, 80.094700),
    ('COLOMBO', 'COLOMBO_AVISSAWELLA',   230, 6.954400, 80.209700),
    ('GAMPAHA', 'GAMPAHA_GAMPAHA',        10, 7.091700, 79.999700),
    ('GAMPAHA', 'GAMPAHA_NEGOMBO',        20, 7.208300, 79.835800),
    ('GAMPAHA', 'GAMPAHA_KATUNAYAKE',     30, 7.169700, 79.884200),
    ('GAMPAHA', 'GAMPAHA_SEEDUWA',        40, 7.126400, 79.881400),
    ('GAMPAHA', 'GAMPAHA_JA_ELA',         50, 7.074400, 79.891900),
    ('GAMPAHA', 'GAMPAHA_WATTALA',        60, 6.989700, 79.891700),
    ('GAMPAHA', 'GAMPAHA_PELIYAGODA',     70, 6.968600, 79.884700),
    ('GAMPAHA', 'GAMPAHA_KELANIYA',       80, 6.955300, 79.921900),
    ('GAMPAHA', 'GAMPAHA_KIRIBATHGODA',   90, 6.978900, 79.926900),
    ('GAMPAHA', 'GAMPAHA_RAGAMA',        100, 7.027200, 79.918600),
    ('GAMPAHA', 'GAMPAHA_KADAWATHA',     110, 7.000000, 79.950000),
    ('GAMPAHA', 'GAMPAHA_BIYAGAMA',      120, 6.950000, 79.983300),
    ('GAMPAHA', 'GAMPAHA_MINUWANGODA',   130, 7.166700, 79.950000),
    ('GAMPAHA', 'GAMPAHA_VEYANGODA',     140, 7.154700, 80.061100),
    ('GAMPAHA', 'GAMPAHA_NITTAMBUWA',    150, 7.140000, 80.096400),
    ('GAMPAHA', 'GAMPAHA_ATTANAGALLA',   160, 7.105800, 80.147800),
    ('GAMPAHA', 'GAMPAHA_MIRIGAMA',      170, 7.242200, 80.127500),
    ('GAMPAHA', 'GAMPAHA_DIVULAPITIYA',  180, 7.221100, 80.019700),
    ('GAMPAHA', 'GAMPAHA_DOMPE',         190, 6.996700, 80.094700),
    ('KALUTARA', 'KALUTARA_KALUTARA',      10, 6.585400, 79.960700),
    ('KALUTARA', 'KALUTARA_PANADURA',      20, 6.713300, 79.904400),
    ('KALUTARA', 'KALUTARA_WADDUWA',       30, 6.666700, 79.933300),
    ('KALUTARA', 'KALUTARA_BANDARAGAMA',   40, 6.713900, 79.988900),
    ('KALUTARA', 'KALUTARA_HORANA',        50, 6.715600, 80.061900),
    ('KALUTARA', 'KALUTARA_INGIRIYA',      60, 6.746100, 80.168300),
    ('KALUTARA', 'KALUTARA_DODANGODA',     70, 6.563600, 80.021900),
    ('KALUTARA', 'KALUTARA_PAYAGALA',      80, 6.517500, 79.979700),
    ('KALUTARA', 'KALUTARA_BERUWALA',      90, 6.478800, 79.982800),
    ('KALUTARA', 'KALUTARA_ALUTHGAMA',    100, 6.433100, 80.000600),
    ('KALUTARA', 'KALUTARA_MATUGAMA',     110, 6.522500, 80.112800),
    ('KALUTARA', 'KALUTARA_AGALAWATTA',   120, 6.547800, 80.153100),
    ('KALUTARA', 'KALUTARA_BULATHSINHALA', 130, 6.583300, 80.183300)
) AS v(district_code, code, display_order, latitude, longitude)
JOIN areas d ON d.code = v.district_code;

-- Districts and towns translated in one statement: both are areas, and splitting them
-- would only invite one half to fall behind the other.
INSERT INTO area_translations (area_id, language, name)
SELECT a.id, t.language, t.name
FROM areas a
JOIN (VALUES
    ('COLOMBO',  'Colombo',  'කොළඹ',  'கொழும்பு'),
    ('GAMPAHA',  'Gampaha',  'ගම්පහ', 'கம்பஹா'),
    ('KALUTARA', 'Kalutara', 'කළුතර', 'களுத்துறை'),
    ('COLOMBO_CITY',          'Colombo',                   'කොළඹ',                    'கொழும்பு'),
    ('COLOMBO_BAMBALAPITIYA', 'Bambalapitiya',             'බම්බලපිටිය',              'பம்பலப்பிட்டி'),
    ('COLOMBO_BORELLA',       'Borella',                   'බොරැල්ල',                 'பொரளை'),
    ('COLOMBO_WELLAWATTE',    'Wellawatte',                'වැල්ලවත්ත',               'வெள்ளவத்தை'),
    ('COLOMBO_DEHIWALA',      'Dehiwala',                  'දෙහිවල',                  'தெஹிவளை'),
    ('COLOMBO_MOUNT_LAVINIA', 'Mount Lavinia',             'ගල්කිස්ස',                'கல்கிசை'),
    ('COLOMBO_MORATUWA',      'Moratuwa',                  'මොරටුව',                  'மொரட்டுவ'),
    ('COLOMBO_NUGEGODA',      'Nugegoda',                  'නුගේගොඩ',                 'நுகேகொடை'),
    ('COLOMBO_NAWALA',        'Nawala',                    'නාවල',                    'நாவல'),
    ('COLOMBO_RAJAGIRIYA',    'Rajagiriya',                'රාජගිරිය',                'ராஜகிரிய'),
    ('COLOMBO_BATTARAMULLA',  'Battaramulla',              'බත්තරමුල්ල',              'பத்தரமுல்லை'),
    ('COLOMBO_KOTTE',         'Sri Jayawardenepura Kotte', 'ශ්‍රී ජයවර්ධනපුර කෝට්ටේ', 'ஸ்ரீ ஜயவர்தனபுர கோட்டே'),
    ('COLOMBO_MAHARAGAMA',    'Maharagama',                'මහරගම',                   'மகரகம'),
    ('COLOMBO_KOTTAWA',       'Kottawa',                   'කොට්ටාව',                 'கொட்டாவ'),
    ('COLOMBO_PILIYANDALA',   'Piliyandala',               'පිළියන්දල',               'பிலியந்தல'),
    ('COLOMBO_KESBEWA',       'Kesbewa',                   'කැස්බෑව',                 'கெஸ்பேவ'),
    ('COLOMBO_HOMAGAMA',      'Homagama',                  'හෝමාගම',                  'ஹோமாகம'),
    ('COLOMBO_MALABE',        'Malabe',                    'මාලබේ',                   'மாலபே'),
    ('COLOMBO_KADUWELA',      'Kaduwela',                  'කඩුවෙල',                  'கடுவெல'),
    ('COLOMBO_KOLONNAWA',     'Kolonnawa',                 'කොලොන්නාව',               'கொலன்னாவ'),
    ('COLOMBO_HANWELLA',      'Hanwella',                  'හංවැල්ල',                 'ஹன்வெல்ல'),
    ('COLOMBO_PADUKKA',       'Padukka',                   'පාදුක්ක',                 'பாதுக்க'),
    ('COLOMBO_AVISSAWELLA',   'Avissawella',               'අවිස්සාවේල්ල',            'அவிசாவளை'),
    ('GAMPAHA_GAMPAHA',      'Gampaha',      'ගම්පහ',      'கம்பஹா'),
    ('GAMPAHA_NEGOMBO',      'Negombo',      'මීගමුව',     'நீர்கொழும்பு'),
    ('GAMPAHA_KATUNAYAKE',   'Katunayake',   'කටුනායක',    'கட்டுநாயக்க'),
    ('GAMPAHA_SEEDUWA',      'Seeduwa',      'සීදුව',      'சீதுவ'),
    ('GAMPAHA_JA_ELA',       'Ja-Ela',       'ජා-ඇල',      'ஜா-எல'),
    ('GAMPAHA_WATTALA',      'Wattala',      'වත්තල',      'வத்தளை'),
    ('GAMPAHA_PELIYAGODA',   'Peliyagoda',   'පෑලියගොඩ',   'பேலியகொடை'),
    ('GAMPAHA_KELANIYA',     'Kelaniya',     'කැලණිය',     'களனி'),
    ('GAMPAHA_KIRIBATHGODA', 'Kiribathgoda', 'කිරිබත්ගොඩ', 'கிரிபத்கொடை'),
    ('GAMPAHA_RAGAMA',       'Ragama',       'රාගම',       'ராகமை'),
    ('GAMPAHA_KADAWATHA',    'Kadawatha',    'කඩවත',       'கடவத்தை'),
    ('GAMPAHA_BIYAGAMA',     'Biyagama',     'බියගම',      'பியகம'),
    ('GAMPAHA_MINUWANGODA',  'Minuwangoda',  'මිනුවන්ගොඩ', 'மினுவாங்கொடை'),
    ('GAMPAHA_VEYANGODA',    'Veyangoda',    'වේයන්ගොඩ',   'வேயங்கொடை'),
    ('GAMPAHA_NITTAMBUWA',   'Nittambuwa',   'නිට්ටඹුව',   'நிட்டம்புவ'),
    ('GAMPAHA_ATTANAGALLA',  'Attanagalla',  'අත්තනගල්ල',  'அத்தனகல்ல'),
    ('GAMPAHA_MIRIGAMA',     'Mirigama',     'මිරිගම',     'மிரிகம'),
    ('GAMPAHA_DIVULAPITIYA', 'Divulapitiya', 'දිවුලපිටිය', 'திவுலப்பிட்டிய'),
    ('GAMPAHA_DOMPE',        'Dompe',        'දොම්පේ',     'தொம்பே'),
    ('KALUTARA_KALUTARA',      'Kalutara',      'කළුතර',       'களுத்துறை'),
    ('KALUTARA_PANADURA',      'Panadura',      'පානදුර',      'பாணந்துறை'),
    ('KALUTARA_WADDUWA',       'Wadduwa',       'වාද්දුව',     'வாத்துவ'),
    ('KALUTARA_BANDARAGAMA',   'Bandaragama',   'බණ්ඩාරගම',    'பண்டாரகம'),
    ('KALUTARA_HORANA',        'Horana',        'හොරණ',        'ஹொரண'),
    ('KALUTARA_INGIRIYA',      'Ingiriya',      'ඉංගිරිය',     'இங்கிரிய'),
    ('KALUTARA_DODANGODA',     'Dodangoda',     'දොඩංගොඩ',     'தொடங்கொடை'),
    ('KALUTARA_PAYAGALA',      'Payagala',      'පයාගල',       'பயாகல'),
    ('KALUTARA_BERUWALA',      'Beruwala',      'බේරුවල',      'பேருவளை'),
    ('KALUTARA_ALUTHGAMA',     'Aluthgama',     'අලුත්ගම',     'அளுத்கமை'),
    ('KALUTARA_MATUGAMA',      'Matugama',      'මතුගම',       'மத்துகம'),
    ('KALUTARA_AGALAWATTA',    'Agalawatta',    'අගලවත්ත',     'அகலவத்தை'),
    ('KALUTARA_BULATHSINHALA', 'Bulathsinhala', 'බුලත්සිංහල',  'புலத்சிங்கள')
) AS v(code, en, si, ta) ON v.code = a.code
CROSS JOIN LATERAL (VALUES ('EN', v.en), ('SI', v.si), ('TA', v.ta)) AS t(language, name);
