-- V5__tutor_profiles.sql
--
-- What a tutor advertises (FR-T1 - FR-T8): one row per tutor, plus the join tables that
-- tie it to the reference vocabulary seeded in V4.
--
-- Three decisions shape this file.
--
-- 1. The profile is its own table, not more columns on `tutors`. The account and the
--    profile have different lifecycles - the account exists from registration and never
--    goes away, the profile is drafted, published and taken down - and only one of the
--    two is ever public. `tutor_id` is UNIQUE, which is what makes the relationship
--    one-to-one in the database rather than only in the mapping.
--
-- 2. Almost every column is nullable, and deliberately so. A draft is a half-filled form
--    by definition; "complete enough to publish" is a rule about the whole row, enforced
--    by TutorProfile.publish(), and a NOT NULL here would stop a tutor saving on Monday
--    and finishing on Tuesday. What is NOT NULL is what has a sensible answer from the
--    first save: the owner, the status, the availability answer and the online flag.
--
-- 3. What a tutor teaches is a foreign key, never text (architecture section 9). A
--    filter and a profile have to be saying the same word for the filter to match, and a
--    join table is what guarantees they are. Medium and ClassFormat are the exception -
--    closed sets with no reference table, stored as their own names under a CHECK.

CREATE TABLE tutor_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tutor_id            BIGINT       NOT NULL,
    headline            VARCHAR(200),
    bio                 VARCHAR(5000),
    photo_url           VARCHAR(500),
    intro_video_url     VARCHAR(500),
    years_of_experience INTEGER,
    -- Rupees. NUMERIC, never a floating-point type: money that rounds is money that is wrong.
    fee_min             NUMERIC(10,2),
    fee_max             NUMERIC(10,2),
    fee_unit            VARCHAR(20),
    home_base_area_id   BIGINT,
    travel_radius_km    INTEGER,
    available_online    BOOLEAN      NOT NULL DEFAULT FALSE,
    availability_status VARCHAR(20)  NOT NULL DEFAULT 'ACCEPTING',
    status              VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    -- The verified badge (FR-R3). Set by an administrator after the document review in
    -- Phase 6, never by the tutor and never as a side effect of publishing.
    verified            BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_at         TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT uq_tutor_profiles_tutor UNIQUE (tutor_id),
    CONSTRAINT fk_tutor_profiles_tutor FOREIGN KEY (tutor_id) REFERENCES tutors (id) ON DELETE CASCADE,
    -- Areas are never deleted, only deactivated, so this needs no cascade; the default
    -- RESTRICT is the point, and it is what stops a referenced area from being removed.
    CONSTRAINT fk_tutor_profiles_home_base FOREIGN KEY (home_base_area_id) REFERENCES areas (id),

    CONSTRAINT ck_tutor_profiles_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'SUSPENDED')),
    CONSTRAINT ck_tutor_profiles_availability CHECK (availability_status IN ('ACCEPTING', 'LIMITED', 'FULL')),
    CONSTRAINT ck_tutor_profiles_fee_unit CHECK (fee_unit IN ('PER_HOUR', 'PER_MONTH', 'PER_CLASS')),
    -- A fee range is all three values or none of them: a number with no unit is not
    -- comparable, and a range with one end is not a range. The entity refuses the same
    -- combination; this is the version that also holds for a data fix applied by hand.
    CONSTRAINT ck_tutor_profiles_fee_range CHECK (
        (fee_min IS NULL AND fee_max IS NULL AND fee_unit IS NULL)
        OR (fee_min IS NOT NULL AND fee_max IS NOT NULL AND fee_unit IS NOT NULL
            AND fee_min >= 0 AND fee_max >= fee_min)),
    CONSTRAINT ck_tutor_profiles_experience CHECK (years_of_experience IS NULL OR years_of_experience >= 0),
    CONSTRAINT ck_tutor_profiles_travel_radius CHECK (travel_radius_km IS NULL OR travel_radius_km >= 0),
    -- A badge with no date is a badge nobody can audit.
    CONSTRAINT ck_tutor_profiles_verified_at CHECK (
        (verified = FALSE AND verified_at IS NULL) OR (verified = TRUE AND verified_at IS NOT NULL))
);

-- Search reads published profiles and nothing else, and shows the verified ones first
-- (FR-S6, FR-R3). This index covers that access path from the day search arrives.
CREATE INDEX idx_tutor_profiles_status_verified ON tutor_profiles (status, verified);
CREATE INDEX idx_tutor_profiles_home_base ON tutor_profiles (home_base_area_id);

-- ---------------------------------------------------------------------------
-- What a tutor teaches: joins to the reference tables
-- ---------------------------------------------------------------------------
--
-- Each has the profile as the first half of its primary key, which is both the
-- uniqueness rule (a subject cannot be listed twice) and the index for "this profile's
-- subjects". The second index is the one search needs: "profiles teaching this subject".

CREATE TABLE tutor_profile_subjects (
    tutor_profile_id BIGINT NOT NULL,
    subject_id       BIGINT NOT NULL,

    CONSTRAINT pk_tutor_profile_subjects PRIMARY KEY (tutor_profile_id, subject_id),
    CONSTRAINT fk_tps_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tps_subject FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

CREATE INDEX idx_tps_subject ON tutor_profile_subjects (subject_id);

CREATE TABLE tutor_profile_exam_levels (
    tutor_profile_id BIGINT NOT NULL,
    exam_level_id    BIGINT NOT NULL,

    CONSTRAINT pk_tutor_profile_exam_levels PRIMARY KEY (tutor_profile_id, exam_level_id),
    CONSTRAINT fk_tpel_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tpel_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_levels (id)
);

CREATE INDEX idx_tpel_exam_level ON tutor_profile_exam_levels (exam_level_id);

CREATE TABLE tutor_profile_syllabuses (
    tutor_profile_id BIGINT NOT NULL,
    syllabus_id      BIGINT NOT NULL,

    CONSTRAINT pk_tutor_profile_syllabuses PRIMARY KEY (tutor_profile_id, syllabus_id),
    CONSTRAINT fk_tpsy_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tpsy_syllabus FOREIGN KEY (syllabus_id) REFERENCES syllabuses (id)
);

CREATE INDEX idx_tpsy_syllabus ON tutor_profile_syllabuses (syllabus_id);

-- Where the tutor will travel to teach in person. Empty for an online-only tutor, which
-- is why the completeness rule accepts either this or available_online.
CREATE TABLE tutor_profile_areas_served (
    tutor_profile_id BIGINT NOT NULL,
    area_id          BIGINT NOT NULL,

    CONSTRAINT pk_tutor_profile_areas_served PRIMARY KEY (tutor_profile_id, area_id),
    CONSTRAINT fk_tpa_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tpa_area FOREIGN KEY (area_id) REFERENCES areas (id)
);

CREATE INDEX idx_tpa_area ON tutor_profile_areas_served (area_id);

-- ---------------------------------------------------------------------------
-- The enum-backed sets and the qualification list
-- ---------------------------------------------------------------------------

CREATE TABLE tutor_profile_mediums (
    tutor_profile_id BIGINT      NOT NULL,
    medium           VARCHAR(20) NOT NULL,

    CONSTRAINT pk_tutor_profile_mediums PRIMARY KEY (tutor_profile_id, medium),
    CONSTRAINT fk_tpm_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_tpm_medium CHECK (medium IN ('SINHALA', 'TAMIL', 'ENGLISH'))
);

CREATE TABLE tutor_profile_class_formats (
    tutor_profile_id BIGINT      NOT NULL,
    class_format     VARCHAR(20) NOT NULL,

    CONSTRAINT pk_tutor_profile_class_formats PRIMARY KEY (tutor_profile_id, class_format),
    CONSTRAINT fk_tpcf_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_tpcf_class_format CHECK (class_format IN ('ONE_TO_ONE', 'SMALL_GROUP', 'MASS_CLASS', 'ONLINE'))
);

-- Qualifications are an embedded value collection, not entities: a claim has no identity
-- of its own, is never queried for, and dies with the profile that lists it. Ordered by
-- display_order because the order the tutor arranged them in is how they read - and that
-- column is also what makes the primary key unique when two lines are otherwise identical.
CREATE TABLE tutor_profile_qualifications (
    tutor_profile_id BIGINT       NOT NULL,
    display_order    INTEGER      NOT NULL,
    title            VARCHAR(200) NOT NULL,
    institution      VARCHAR(200) NOT NULL,
    year_awarded     INTEGER      NOT NULL,

    CONSTRAINT pk_tutor_profile_qualifications PRIMARY KEY (tutor_profile_id, display_order),
    CONSTRAINT fk_tpq_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_tpq_year CHECK (year_awarded BETWEEN 1900 AND 2100)
);
