-- V6__verification_documents.sql
--
-- Qualification documents submitted for manual review (FR-T7), and the review decision
-- taken on each.
--
-- The row holds a storage key, never the bytes. Files live behind the FileStorage
-- interface - local disk today, object storage later - and the key is opaque to this
-- table as well, so moving the store is a code change with no data migration behind it.
--
-- Three columns describe the content: content_type is what the platform DETECTED from
-- the bytes at upload, never what the client declared; size_bytes is what was actually
-- written; original_filename is the tutor's own label, kept so they can tell one
-- certificate from another and used for nothing else. None of the three is trusted later
-- to decide what the file is.
--
-- Note what is absent: no public URL and no path. A document is reachable only through
-- an endpoint that authorises the caller on every read, and a column holding a URL would
-- quietly create a second way in.

CREATE TABLE verification_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tutor_id          BIGINT       NOT NULL,
    document_type     VARCHAR(30)  NOT NULL,
    storage_key       VARCHAR(200) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    review_notes      VARCHAR(1000),
    reviewed_by_id    BIGINT,
    reviewed_at       TIMESTAMP(6) WITH TIME ZONE,

    -- One key, one document. The application generates a UUID per upload, so a duplicate
    -- here would mean two rows sharing a file and either one able to delete it.
    CONSTRAINT uq_verification_documents_storage_key UNIQUE (storage_key),
    -- A deleted account takes its documents with it: an identity document has no reason
    -- to outlive the person who sent it.
    CONSTRAINT fk_verification_documents_tutor FOREIGN KEY (tutor_id) REFERENCES tutors (id) ON DELETE CASCADE,
    -- The reviewer is kept for audit, so this deliberately does NOT cascade: an admin
    -- account cannot be removed while its decisions are on record.
    CONSTRAINT fk_verification_documents_reviewer FOREIGN KEY (reviewed_by_id) REFERENCES admins (id),

    CONSTRAINT ck_verification_documents_type CHECK (
        document_type IN ('NIC', 'DEGREE_CERTIFICATE', 'TEACHING_CERTIFICATE', 'OTHER')),
    CONSTRAINT ck_verification_documents_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_verification_documents_size CHECK (size_bytes > 0),
    -- A decision always has an author and a moment, and a pending document has neither.
    -- The entity enforces this; the constraint is what also holds for a fix applied by hand.
    CONSTRAINT ck_verification_documents_review CHECK (
        (status = 'PENDING' AND reviewed_by_id IS NULL AND reviewed_at IS NULL)
        OR (status <> 'PENDING' AND reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL))
);

-- "This tutor's documents, newest first" - the tutor's own list, and the per-tutor count
-- the upload limit is checked against.
CREATE INDEX idx_verification_documents_tutor ON verification_documents (tutor_id, created_at DESC);

-- The reviewer's queue: everything still pending, oldest first, so nobody waits twice.
CREATE INDEX idx_verification_documents_status ON verification_documents (status, created_at);
