-- V8__enquiries.sql
--
-- On-platform first contact (FR-E1 - FR-E3) and the parent's shortlist (FR-P1 - FR-P3).
--
-- This is the schema behind objective OBJ-4: a parent and a tutor must be able to hold a
-- useful conversation here, before either of them has the other's phone number. Four
-- decisions follow from that.
--
-- 1. The message body is in enquiry_messages and nowhere else. The opening message is the
--    first row of the thread rather than a column on the enquiry, so there is exactly one
--    place a body is stored, one place it is scrubbed of contact details, and no second
--    copy to drift out of step with the first.
--
-- 2. first_response_at is the reveal switch, and it is a timestamp rather than a boolean.
--    "Has the tutor replied yet" and "when did the contact details become visible" are the
--    same question, and answering it from a stored moment is what makes a reveal auditable.
--
-- 3. What the parent is asking about is a foreign key, never text (architecture section 9).
--    An enquiry names a subject and an exam level from the same vocabulary the search
--    filters and the tutor profiles use, so a tutor's inbox and their profile are describing
--    the same thing.
--
-- 4. Neither the parent nor the tutor cascades. A thread is a record that contact happened,
--    and it belongs to both sides; accounts are soft-deleted (AccountStatus.DELETED), so
--    the row that would trigger a cascade here is one that in practice never goes away. The
--    child profile is the exception - that one is genuinely deletable, and losing it must
--    blank a column rather than delete a conversation.

CREATE TABLE enquiries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    parent_id         BIGINT      NOT NULL,
    tutor_id          BIGINT      NOT NULL,
    -- Which child this is about. Optional: an adult student enquiring for themselves has
    -- no child profile, and FR-A5 makes the sub-profile a convenience, not a requirement.
    child_profile_id  BIGINT,
    subject_id        BIGINT      NOT NULL,
    exam_level_id     BIGINT      NOT NULL,
    preferred_format  VARCHAR(20) NOT NULL,
    -- "Where, or online" - exactly one of the two, enforced below. A parent who says
    -- "online" is not saying "online in Nugegoda".
    preferred_area_id BIGINT,
    online            BOOLEAN     NOT NULL DEFAULT FALSE,
    status            VARCHAR(20) NOT NULL DEFAULT 'SENT',
    first_response_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT fk_enquiries_parent FOREIGN KEY (parent_id) REFERENCES parents (id),
    CONSTRAINT fk_enquiries_tutor FOREIGN KEY (tutor_id) REFERENCES tutors (id),
    CONSTRAINT fk_enquiries_child FOREIGN KEY (child_profile_id) REFERENCES child_profiles (id) ON DELETE SET NULL,
    -- Reference values are retired, never deleted, so the default RESTRICT is the point:
    -- it stops a subject being removed while enquiries still name it.
    CONSTRAINT fk_enquiries_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
    CONSTRAINT fk_enquiries_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_levels (id),
    CONSTRAINT fk_enquiries_area FOREIGN KEY (preferred_area_id) REFERENCES areas (id),

    CONSTRAINT ck_enquiries_status CHECK (status IN ('SENT', 'VIEWED', 'RESPONDED', 'CLOSED', 'SPAM')),
    CONSTRAINT ck_enquiries_format CHECK (
        preferred_format IN ('ONE_TO_ONE', 'SMALL_GROUP', 'MASS_CLASS', 'ONLINE')),
    -- An area or online, never both and never neither.
    CONSTRAINT ck_enquiries_place CHECK (
        (online = TRUE AND preferred_area_id IS NULL)
        OR (online = FALSE AND preferred_area_id IS NOT NULL)),
    -- RESPONDED is defined by the moment the tutor answered. The entity sets the two
    -- together; this is the version that also holds for a fix applied by hand.
    CONSTRAINT ck_enquiries_responded CHECK (status <> 'RESPONDED' OR first_response_at IS NOT NULL)
);

-- The two inbox queries, which are the same query read from opposite ends: "my threads,
-- optionally filtered by status, newest first".
CREATE INDEX idx_enquiries_tutor ON enquiries (tutor_id, status, created_at DESC);
CREATE INDEX idx_enquiries_parent ON enquiries (parent_id, status, created_at DESC);

-- One live thread per parent-tutor pair. The service refuses the second one with a
-- readable error; this index is what holds when two requests arrive at once. Closed and
-- spam threads are excluded, so a conversation can legitimately be reopened later.
CREATE UNIQUE INDEX uq_enquiries_open_pair ON enquiries (parent_id, tutor_id)
    WHERE status IN ('SENT', 'VIEWED', 'RESPONDED');

-- ---------------------------------------------------------------------------
-- The thread
-- ---------------------------------------------------------------------------
--
-- sender_id points at users, not at parents or tutors: a message is from whichever of the
-- two participants wrote it, and the thread is read as one ordered list regardless.
--
-- read_at is on the message rather than a per-thread counter because an unread badge has
-- to survive a participant reading half a thread and closing the tab.

CREATE TABLE enquiry_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    enquiry_id BIGINT        NOT NULL,
    sender_id  BIGINT        NOT NULL,
    -- Already scrubbed of phone numbers and email addresses when the thread is still
    -- pre-reveal. What is stored is what both sides see; there is no unscrubbed original.
    body       VARCHAR(4000) NOT NULL,
    read_at    TIMESTAMP(6) WITH TIME ZONE,

    -- The thread is part of the enquiry aggregate and has no meaning without it.
    CONSTRAINT fk_enquiry_messages_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries (id) ON DELETE CASCADE,
    CONSTRAINT fk_enquiry_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT ck_enquiry_messages_body CHECK (length(btrim(body)) > 0)
);

-- Reading a thread in order, and counting what the other side has not read yet.
CREATE INDEX idx_enquiry_messages_enquiry ON enquiry_messages (enquiry_id, created_at);

-- ---------------------------------------------------------------------------
-- Shortlists (FR-P1)
-- ---------------------------------------------------------------------------
--
-- Saving a tutor is not contacting one: no masking question arises here, and the note is
-- the parent's own reminder, never shown to the tutor.

CREATE TABLE shortlists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    parent_id  BIGINT NOT NULL,
    tutor_id   BIGINT NOT NULL,
    note       VARCHAR(500),

    -- Saving the same tutor twice is the same shortlist entry, not a second one.
    CONSTRAINT uq_shortlists_pair UNIQUE (parent_id, tutor_id),
    CONSTRAINT fk_shortlists_parent FOREIGN KEY (parent_id) REFERENCES parents (id) ON DELETE CASCADE,
    CONSTRAINT fk_shortlists_tutor FOREIGN KEY (tutor_id) REFERENCES tutors (id) ON DELETE CASCADE
);

-- "My shortlist, most recently saved first."
CREATE INDEX idx_shortlists_parent ON shortlists (parent_id, created_at DESC);
