-- V9__audit_log_and_metrics.sql
--
-- What the pilot needs to be operated and judged (Phase 5.1): a durable record of every
-- verification, moderation and contact-reveal action (NFR-10), and a search count that
-- survives a restart (OBJ-6).
--
-- No admin account is seeded here. A migration is committed, and an administrator's
-- credentials must never be: the first admin is provisioned at startup from environment
-- variables by AdminBootstrapRunner, and nothing anywhere lets anybody register as one.

-- ---------------------------------------------------------------------------
-- Audit log (NFR-10)
-- ---------------------------------------------------------------------------
--
-- Three decisions shape this table.
--
-- 1. The actor and the target are ids, not foreign keys. One table records actions on
--    accounts, profiles, documents and enquiries, and a record of what happened must neither
--    be deleted with the rows it names nor stop those rows being removed: evidence records
--    the past, it does not constrain it. Accounts are soft-deleted, so in practice the ids
--    keep resolving; the point is that the audit trail does not depend on it.
--
-- 2. before_value and after_value are JSONB snapshots of only the fields the action
--    changed, written by the application. They are evidence, not a replica: nothing reads
--    them back into an entity, so they do not need to track the schema of the row they
--    describe.
--
-- 3. The table is append-only, enforced by a trigger rather than by convention. An audit
--    trail anyone with write access can quietly edit is not one; a correction is a new row.

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Who acted: a users.id.
    actor_id     BIGINT        NOT NULL,
    action       VARCHAR(40)   NOT NULL,
    target_type  VARCHAR(30)   NOT NULL,
    target_id    BIGINT        NOT NULL,
    before_value JSONB,
    after_value  JSONB,
    -- The moderator's stated reason, when the action takes one.
    reason       VARCHAR(1000),
    -- IPv6 at its longest textual form is 45 characters. Null for an action with no
    -- request behind it.
    ip_address   VARCHAR(45),

    CONSTRAINT ck_audit_logs_action CHECK (action IN (
        'DOCUMENT_VIEWED', 'DOCUMENT_APPROVED', 'DOCUMENT_REJECTED',
        'TUTOR_VERIFIED', 'TUTOR_VERIFICATION_REVOKED',
        'PROFILE_SUSPENDED', 'PROFILE_REINSTATED',
        'ACCOUNT_SUSPENDED', 'ACCOUNT_REINSTATED',
        'CONTACT_REVEALED')),
    CONSTRAINT ck_audit_logs_target_type CHECK (
        target_type IN ('USER', 'TUTOR_PROFILE', 'VERIFICATION_DOCUMENT', 'ENQUIRY'))
);

-- "Everything that happened to this tutor / document / thread, newest first."
CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id, created_at DESC);
-- "Everything this administrator did."
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_id, created_at DESC);

CREATE FUNCTION audit_logs_forbid_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_forbid_change();

-- ---------------------------------------------------------------------------
-- Search volume (OBJ-6)
-- ---------------------------------------------------------------------------
--
-- One row per day, not one per search. The pilot's question is "how many searches", and
-- a counter answers it without storing what anybody searched for - which would be a
-- record of a parent's child's subjects and neighbourhood that nobody has asked to keep.
--
-- The day is the calendar day in Asia/Colombo, so a date range on the metrics screen
-- means the same thing for searches as it does for registrations and enquiries.

CREATE TABLE search_daily_counts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    day          DATE   NOT NULL,
    search_count BIGINT NOT NULL DEFAULT 0,

    -- The upsert that increments the counter conflicts on this, which is what makes two
    -- concurrent searches on a new day produce one row with a count of two.
    CONSTRAINT uq_search_daily_counts_day UNIQUE (day),
    CONSTRAINT ck_search_daily_counts_count CHECK (search_count >= 0)
);

-- The metrics summary counts enquiries by the day they were sent. V8 indexes enquiries by
-- participant only, so a date-range count over every enquiry would otherwise scan the table.
CREATE INDEX idx_enquiries_created_at ON enquiries (created_at);
CREATE INDEX idx_users_created_at ON users (created_at);
